# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "qjKKoXqkCySCkbb6/BOAlZ/OLD/EwiIeHil6mLhAtXeXg3OMnzirdK3OlM1mNijRT5SSzE/aXvVnBpAxw4GxXsw9xcSSJGvtf4JQgKKlFZeIMN2+s1LVQ3Ke0kLHVjdhz5f7mnxbN/aNpYQ/Dlnv2ENa5clVNJK3C9Xci0Xvgt0DgAK7nHbl/fEGXE6n1Iun5h09N5ir4WGwN+aWLMOZPKA1rV5jU1f+TMbwxLTi4ZQfWhGkQTkTl0kVyh7tAmQvDQsJZxZp+J+DMheZARanNy7aoxpHn8owGr94LKELuMH5v2vV23RmMTfF18N2GKs1w6ZwFnfV5aVpFGdcWG8QDkaNqYjOATcOjsZmGeLl8k2WJRaEX6Z4CssKxPXCVy1/OaNvt7yWMixbIvFOl17L8R0ewljFFNPKM1y8oUfonjRO93QNA+W6RabPh1fFxSxtqBL/lBKFzPj/UWjAvxJFIpjx6btBr2ELWDILoqeqp0KwBVK7uZGt/xpmKH/OsbaB5rp4Mv9Mn7JIA9FAI1Pf/P7pQE0LBexGAHeUokKKQCwC9I2QCb2ehnSzAYSkXcVrashioqlef8/tWyVZHc0IBIMnPTVNLxoeVi3ogXedezXjfvpL6wb3aFVmQFfDD6o1lhcCQq21AU2/MRc3GTPezOi3PFA3KlA80SFqcgkTJxw="


before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
