travis:
  secure:
    BINSTAR_TOKEN: qjKKoXqkCySCkbb6/BOAlZ/OLD/EwiIeHil6mLhAtXeXg3OMnzirdK3OlM1mNijRT5SSzE/aXvVnBpAxw4GxXsw9xcSSJGvtf4JQgKKlFZeIMN2+s1LVQ3Ke0kLHVjdhz5f7mnxbN/aNpYQ/Dlnv2ENa5clVNJK3C9Xci0Xvgt0DgAK7nHbl/fEGXE6n1Iun5h09N5ir4WGwN+aWLMOZPKA1rV5jU1f+TMbwxLTi4ZQfWhGkQTkTl0kVyh7tAmQvDQsJZxZp+J+DMheZARanNy7aoxpHn8owGr94LKELuMH5v2vV23RmMTfF18N2GKs1w6ZwFnfV5aVpFGdcWG8QDkaNqYjOATcOjsZmGeLl8k2WJRaEX6Z4CssKxPXCVy1/OaNvt7yWMixbIvFOl17L8R0ewljFFNPKM1y8oUfonjRO93QNA+W6RabPh1fFxSxtqBL/lBKFzPj/UWjAvxJFIpjx6btBr2ELWDILoqeqp0KwBVK7uZGt/xpmKH/OsbaB5rp4Mv9Mn7JIA9FAI1Pf/P7pQE0LBexGAHeUokKKQCwC9I2QCb2ehnSzAYSkXcVrashioqlef8/tWyVZHc0IBIMnPTVNLxoeVi3ogXedezXjfvpL6wb3aFVmQFfDD6o1lhcCQq21AU2/MRc3GTPezOi3PFA3KlA80SFqcgkTJxw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
